set -g mouse on
set -g history-limit 50000
set -g mode-keys vi

bind -T root WheelUpPane if-shell -F -t = '#{mouse_any_flag}' 'send-keys -M' 'copy-mode -e'
bind -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X scroll-down
bind -T copy-mode-emacs WheelUpPane send-keys -X scroll-up
bind -T copy-mode-emacs WheelDownPane send-keys -X scroll-down
