#!/bin/bash

IMAGE_REGISTRY="${AGENT_IMAGE_REGISTRY:-ghcr.io/mark0725/agent-go-docker}"

IMAGE="${IMAGE_REGISTRY}:latest"
EXTRA_ARGS=""

PROJECT_ID=${PROJECT_ID:-`pwd|sed  's/\//_/g'`}
AGENT_ID="${AGENT_ID:-default}"

PROJECT_HOME="${PROJECT_HOME:-`pwd`}"
CLAUDE_HOME="${CLAUDE_HOME:-${HOME}/.claude}"
AGENT_HOME="${AGENT_HOME:-${HOME}/.agents}"
AGENT_WORKSPACE="${AGENT_WORKSPACE:-/workspace/${PROJECT_ID}}"

CMD_NAME="${CMD_NAME:-claude}"

mkdir -p ${AGENT_HOME} 
mkdir -p ${CLAUDE_HOME} 

# 解析选项
while [ $# -gt 0 ]; do
    case "$1" in
        --java8)
            IMAGE="${IMAGE_REGISTRY}:java8"
            shift
            ;;
        --java)
            IMAGE="${IMAGE_REGISTRY}:java17"
            shift
            ;;
        --java17)
            IMAGE="${IMAGE_REGISTRY}:java17"
            shift
            ;;
        --java21)
            IMAGE="${IMAGE_REGISTRY}:java21"
            shift
            ;;
        --java25)
            IMAGE="${IMAGE_REGISTRY}:java25"
            shift
            ;;
        --go)
            IMAGE="${IMAGE_REGISTRY}:go"
            shift
            ;;
        --rust)
            IMAGE="${IMAGE_REGISTRY}:rust"
            shift
            ;;
        *)
            EXTRA_ARGS="$EXTRA_ARGS $1"
            shift
            ;;
    esac
done

docker run -it --rm --network=host \
    --user 0 \
    -e "HOST_UID=$(id -u)" \
    -e "HOST_GID=$(id -g)" \
    -e "HOME=/home/node" \
    -e "AGENT_ID=${AGENT_ID}" \
    -v node_home:/home/node \
    -v "${PROJECT_HOME}:/workspace/${PROJECT_ID}" \
    -v "${CLAUDE_HOME}:/home/node/.claude" \
    -v "${AGENT_HOME}:/home/node/.agents" \
    -w "${AGENT_WORKSPACE}" \
  "${IMAGE}" claude --dangerously-skip-permissions --allowedTools "Edit,Write,Bash" ${EXTRA_ARGS}
